language: cpp

compiler: clang

before_install:
   - wget http://llvm.org/releases/3.6.1/clang+llvm-3.6.1-x86_64-linux-gnu-ubuntu-14.04.tar.xz
   - tar xJf clang+llvm-3.6.1-x86_64-linux-gnu-ubuntu-14.04.tar.xz
   - export PATH=$PWD/clang+llvm-3.6.1-x86_64-linux-gnu-ubuntu-14.04/bin:$PATH

install: ./build/linux

script: make all && ./bin/Debug/tests

branches:
   only:
      - master

notifications:
   email: false
   webhooks:
      urls:
         - https://webhooks.gitter.im/e/51883e19ced23443dd4e
      on_success: change
      on_failure: always
      on_start: never


