os: osx

language: cpp

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

install: ./build/xcode

script: xctool -workspace flair.xcworkspace -scheme tests build && ./bin/Debug/tests

branches:
   only:
      - master

notifications:
   email: false
   slack: libflair:ICPTqs51urPRmzgz5JPROHdT
