sudo: false
os:
  - osx

language: cpp

install: ./build/travis

script: xctool -workspace flair.xcworkspace -scheme tests build && ./bin/Debug/tests

branches:
   only:
      - master

notifications:
   email: false
   slack: libflair:ICPTqs51urPRmzgz5JPROHdT
