sudo: false
os:
  - osx

language: cpp

install: ./build/xcode

script: xcodebuild -workspace flair.xcworkspace -scheme tests && ./bin/Debug/tests

branches:
   only:
      - master

notifications:
   email: false
   slack: libflair:ICPTqs51urPRmzgz5JPROHdT
