language: cpp

compiler: clang

install: ./build/linux

script: make all && ./bin/Debug/tests

branches:
   only:
      - master

notifications:
   email: false
   webhooks:
      urls:
         - https://webhooks.gitter.im/e/51883e19ced23443dd4e
      on_success: change
      on_failure: always
      on_start: never


